# Site settings
title: Sync For Science
tag_text: Helping patients share EHR data with research
description: technology to help patients share data with research
baseurl: ""
font-awesome-include: true
markdown: kramdown

exclude: ["README.md"]
